# NNTI Assignment 2
## Prepared by: Team 83
## Team Members:
### Name: Ratnadeep Chakraborty
#### Student ID: 7022859
#### Email: rach00002@stud.uni-saarland.de

### Name: Md Mobashir Rahman
#### Student ID: 7059086
#### Email: mdra00001@stud.uni-saarland.de

In [1]:
import numpy as np
import json
import csv
import torch
from torch.utils.data import Dataset, DataLoader, random_split
from torch.nn.utils.rnn import pad_sequence

The following two cells are a suggestion on accessing the files. You are free to ignore these!

In [2]:
with open("data/Dataset1/data.json", "r") as f:
    data_1 = json.load(f)
data_1

[{'tokens': [101,
   2175,
   2127,
   18414,
   17583,
   2391,
   1010,
   4689,
   1012,
   1012,
   2800,
   2069,
   1999,
   11829,
   2483,
   1050,
   2307,
   2088,
   2474,
   1041,
   28305,
   1012,
   1012,
   1012,
   25022,
   2638,
   2045,
   2288,
   26297,
   28194,
   1012,
   1012,
   1012,
   102],
  'label': 0},
 {'tokens': [101,
   7929,
   2474,
   2099,
   1012,
   1012,
   1012,
   16644,
   15536,
   2546,
   1057,
   2006,
   2072,
   1012,
   1012,
   1012,
   102],
  'label': 0},
 {'tokens': [101,
   2489,
   4443,
   1999,
   1016,
   1037,
   1059,
   2243,
   2135,
   4012,
   2361,
   2000,
   2663,
   6904,
   2452,
   2345,
   1056,
   25509,
   2015,
   7398,
   2089,
   2384,
   1012,
   3793,
   6904,
   2000,
   6584,
   12521,
   2487,
   2000,
   4374,
   4443,
   3160,
   1006,
   2358,
   2094,
   19067,
   2102,
   3446,
   1007,
   1056,
   1004,
   1039,
   1005,
   1055,
   6611,
   5511,
   19961,
   22407,
   18613,
   23352,
   7840,


In [3]:
with open("data/Dataset2/data.csv", "r") as file:
    for row in csv.DictReader(file):
        print(row)

{'id': '0', 'sudden_fever': '1.0', 'headache': '1.0', 'mouth_bleed': '0.0', 'nose_bleed': '1.0', 'muscle_pain': '1.0', 'joint_pain': '1.0', 'vomiting': '1.0', 'rash': '0.0', 'diarrhea': '1.0', 'hypotension': '1.0', 'pleural_effusion': '1.0', 'ascites': '1.0', 'gastro_bleeding': '0.0', 'swelling': '0.0', 'nausea': '1.0', 'chills': '1.0', 'myalgia': '0.0', 'digestion_trouble': '0.0', 'fatigue': '1.0', 'skin_lesions': '0.0', 'stomach_pain': '1.0', 'orbital_pain': '0.0', 'neck_pain': '1.0', 'weakness': '1.0', 'back_pain': '1.0', 'weight_loss': '1.0', 'gum_bleed': '1.0', 'jaundice': '1.0', 'coma': '1.0', 'diziness': '0.0', 'inflammation': '0.0', 'red_eyes': '1.0', 'loss_of_appetite': '0.0', 'urination_loss': '0.0', 'slow_heart_rate': '0.0', 'abdominal_pain': '0.0', 'light_sensitivity': '1.0', 'yellow_skin': '0.0', 'yellow_eyes': '0.0', 'facial_distortion': '0.0', 'microcephaly': '0.0', 'rigor': '0.0', 'bitter_tongue': '1.0', 'convulsion': '0.0', 'anemia': '1.0', 'cocacola_urine': '0.0', 'hy

In [4]:
#Implement this!
class TokenDataset(Dataset):
    def __init__(self, data_path):
        super().__init__()

        with open(data_path) as f:
            data_1 = json.load(f)  

        self.x = []
        self.y = []
        self.n_samples = len(data_1)

        for data in data_1:
            tokens = data['tokens']
            label = data['label']

            token_tensor = torch.tensor(tokens, dtype=torch.long)
            self.x.append(token_tensor)
            self.y.append(label)

        self.x = pad_sequence(self.x, batch_first=True)
        self.y = torch.tensor(self.y, dtype=torch.long)     

    def __len__(self):
        return self.n_samples
    
    def __getitem__(self, index):
        return self.x[index], self.y[index]
    


class TokenDataLoader(DataLoader):
    def __init__(self, dataset, batch_size=32, shuffle=True):
        super().__init__(dataset, batch_size=batch_size, shuffle=shuffle)

In [5]:
dataset = TokenDataset("data/Dataset1/data.json")

train_size = int(0.8 * len(dataset))
test_size = len(dataset) - train_size
train_data, test_data = random_split(dataset, [train_size, test_size])

#Separate the dataset in train and test datasets at random

train_loader = TokenDataLoader(train_data, batch_size=16, shuffle=True) #Dataloader for the training part of the dataset only

for batch in train_loader:
    tokens, labels = batch  

    print(tokens[:5])
    print(labels[:5])
    
    break 

tensor([[  101,  2204,   999,  ...,     0,     0,     0],
        [  101,  2009,  4618,  ...,     0,     0,     0],
        [  101, 16215,  3215,  ...,     0,     0,     0],
        [  101,  3376,  3606,  ...,     0,     0,     0],
        [  101,  2024,  2017,  ...,     0,     0,     0]])
tensor([0, 0, 0, 0, 0])


Test correctness here (do not change the cell below)

In [6]:
X, y = next(iter(train_loader))
print(X)
print(y)

tensor([[ 101, 2821, 1047,  ...,    0,    0,    0],
        [ 101, 2425, 2033,  ...,    0,    0,    0],
        [ 101, 2027, 1054,  ...,    0,    0,    0],
        ...,
        [ 101, 9805, 2361,  ...,    0,    0,    0],
        [ 101, 1057, 5256,  ...,    0,    0,    0],
        [ 101, 4931, 2054,  ...,    0,    0,    0]])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0])


In [7]:
#Implement this!
class CSVDataset(Dataset):
    def __init__(self, data_path):
        super().__init__()
        data = []
        prognosis_labels = set()
        self.encoded_data = []
        self.x = []
        self.y = []

        with open(data_path, 'r') as file:
            reader = csv.reader(file)
            headers = next(reader)  
            for row in reader:
                data.append(row)
                prognosis_labels.add(row[-1])  

        prognosis_labels = sorted(list(prognosis_labels))

        one_hot_matrix = self.one_hot_encoding(prognosis_labels)

        for row in data:
            symptoms = row[:-1]
            prognosis = row[-1]
            one_hot = one_hot_matrix[prognosis]
            encoded_row = symptoms + one_hot
            self.encoded_data.append(encoded_row)

        for row in self.encoded_data:
            features = [float(value) for value in row[:64]]
            label = [int(value) for value in row[65:]]       
            self.x.append(features)
            self.y.append(label)

        self.x = torch.tensor(self.x, dtype=torch.float32)
        self.y = torch.tensor(self.y, dtype=torch.float32) 

    def __getitem__(self, index):
        return self.x[index], self.y[index]

    def one_hot_encoding(self, prognosis_labels):
        one_hot_matrix = {}
        for i in range(len(prognosis_labels)):
            label = prognosis_labels[i]
            one_hot_vector = []
            for j in range(len(prognosis_labels)):
                if i == j:
                    one_hot_vector.append(1)
                else:
                    one_hot_vector.append(0)
            one_hot_matrix[label] = one_hot_vector

        return one_hot_matrix    

    def __len__(self):    
        return len(self.encoded_data)  


class CSVDataLoader(DataLoader):
    def __init__(self, dataset, batch_size=6, shuffle=False):
        super().__init__(dataset, batch_size=batch_size, shuffle=shuffle)

In [8]:
dataset = CSVDataset("data/Dataset2/data.csv")

train_loader = CSVDataLoader(dataset, batch_size=6, shuffle=False)

for batch in train_loader:
    features, labels = batch
    print(features.shape)
    print(labels.shape)
    break  



torch.Size([6, 64])
torch.Size([6, 11])


Test correctness here (do not change the cell below)

In [9]:
X, y = next(iter(train_loader))
print(X.shape)
print(y.shape)

torch.Size([6, 64])
torch.Size([6, 11])
